# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "power-margin-optimizer"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in these schemas will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# Maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by the database pooler.
pooler_port = 54329
# The database major version to use. Accepted values are 12, 13, 14, 15.
major_version = 15

[db.pooler]
enabled = false
# Port to use for the local connection pooler URL.
port = 54329
# Specifies when a server connection can be reused by different clients.
# Possible values: transaction, session.
pool_mode = "transaction"
# How many server connections to allow per connection pool.
default_pool_size = 20
# Maximum number of client connections allowed.
max_client_conn = 100

[realtime]
enabled = true
# Bind realtime via either IPv4 or IPv6. (default: IPv6)
# bind_ipv4 = false
# Port to use for the realtime URL.
port = 54323
# Maximum amount of concurrent websocket connections.
max_ws_connections = 1000

[studio]
enabled = true
# Port to use for the Studio URL.
port = 54324

# Email testing server. Emails sent with the local dev setup are not actually sent - instead, they
# are intercepted and can be viewed in the web UI.
[inbucket]
enabled = true
# Port to use for the email testing server web UI.
port = 54325
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54326
# pop3_port = 54327

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (7 days).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow the ability to generate email OTPs by endpoint.
enable_signup = true
# Controls the minimum amount of time that must pass before sending another signup confirmation or password reset email.
max_frequency = "10s"

# Configure the local development SMTP server which is used by the local dev setup and when
# invoking supabase functions serve.
[smtp]
enabled = true
host = "localhost"
port = 54326
sender_name = "PostgreSQL"
sender_address = "admin@localhost"

[functions.sync-products]
verify_jwt = false